name: Docker Build

on: [push, workflow_dispatch]

env:
  REGISTRY: docker.io
  IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/yuanbao-free-api

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - name: Checkout
      uses: actions/checkout@v4
            # 新增磁盘空间深度清理步骤 [4,5](@ref)
    - name: Free Disk Space
      uses: jlumbroso/free-disk-space@main
      with:
          swap-storage: true  # 释放交换空间
          docker-images: ${{ github.event_name != 'schedule' }}  # 非定期任务清理镜像
          dotnet: true       # 已手动清理 .NET SDK
          tool-cache: true  # 保留 /opt/hostedtoolcache 基础工具链
    - name: 磁盘使用情况
      run: |
          echo "▂▂▂▂▂▂▂▂ 磁盘使用情况 ▂▂▂▂▂▂▂▂"
          df -h /


    - name: Setup Docker
      run: |
        sudo systemctl start docker
        sudo systemctl enable docker

    - name: Clean Docker Resources
      run: |
        docker system prune -a --volumes --force
        docker system df -v

    # Docker Hub认证登录[3,5](@ref)
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # 构建并推送镜像[1,7](@ref)
    - name: Build and Push
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/arm64
        push: ${{ github.event_name != 'pull_request' }}
        tags: |
          ${{ env.IMAGE_NAME }}:latest
          ${{ env.IMAGE_NAME }}:${{ github.sha }}
